apiVersion: v1
kind: Pod
metadata:
  labels:
    app: spring-build-ci
spec:
  containers:
    - name: maven
      image: maven:3.9.6-eclipse-temurin-11
      command:
        - cat
      tty: true
      volumeMounts:
        - name: m2
          mountPath: /root/.m2/
    - name: docker-tools
      image: rmkanda/docker-tools:latest
      command:
        - cat
      tty: true
      volumeMounts:
        - mountPath: /var/run
          name: docker-sock
        - mountPath: /tmp/trivycache/
          name: trivycache
    - name: slscan
      image: shiftleft/sast-scan
      imagePullPolicy: Always
      command:
        - cat
      tty: true

    - name: trufflehog
      image: rmkanda/trufflehog
      command:
        - cat
      tty: true
    - name: licensefinder
      image: licensefinder/license_finder
      command:
        - cat
      tty: true
  volumes:
    - name: m2
      hostPath:
        path: /tmp/.m2/
    - name: docker-sock
      hostPath:
        path: /var/run
    - name: trivycache
      hostPath:
        path: /tmp/trivycache/

